server:
  tomcat:
    connection-timeout: 310s     # ★ Nginx보다 살짝 여유

spring:
  mvc:
    async:
      request-timeout: 305s      # 비동기 컨트롤러(있다면) 타임아웃 상향
  datasource:
    url: jdbc:mysql://db:3306/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

flask:
  server:
    url: http://crawler:5001
crawler:
  api:
    url: http://crawler:5001

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000  # 1시간 (밀리초)
  refresh-token-validity: 604800000  # 7일 (밀리초)

